from fastapi import APIRouter, Depends, Request

from app.api.dependencies.security import get_current_user, require_permission
from app.api.dependencies.supervisor import get_supervisor
from app.api.presenters.chat_presenter import ChatPresenter
from app.api.schemas.request import ChatRequest
from app.api.schemas.response import ChatResponse
from app.graph.supervisor.supervisor import Supervisor
from app.platform.tracing.context import get_execution_id
from app.schemas.context import UserContext, VistaContext

router = APIRouter(prefix="/chat", tags=["chat"])

@router.post("", response_model=ChatResponse, dependencies=[Depends(require_permission("read:chat"))])
async def chat(
    request: Request,
    payload: ChatRequest,
    supervisor: Supervisor = Depends(get_supervisor),
    current_user: dict = Depends(get_current_user)
):
    # Retrieve execution context generated by TracingMiddleware
    execution_id = request.state.execution_id or get_execution_id()
    
    # Initialize the internal VistaContext based on API payload
    context = VistaContext(
        user=UserContext(
            user_id=current_user.get("sub", "unknown"),
            role=current_user.get("role", "viewer"),
            allowed_cameras=current_user.get("allowed_cameras", [])
        ),
        conversation_id=payload.conversation_id or execution_id,
        current_query=payload.query
    )
    
    # Optional constraint
    if payload.camera_ids:
        # Pass constraint via state or refine query (simplified here)
        context.current_query += f" (Focus on cameras: {', '.join(payload.camera_ids)})"

    # Execute workflow
    result = await supervisor.run(context)
    
    # If the pipeline failed entirely, it still returns a valid response model with status='error'
    # We do not raise an HTTP 500 WorkflowError here, because agentic failures (like LLM parse errors)
    # should be returned as blocked/error messages to the client.
        
    # Translate to external representation
    response_model = ChatPresenter.present(result, execution_id, context.execution_time_ms)
    return response_model
