import json
from uuid import uuid4

from app.domain.models.reasoning_context import ReasoningContext
from app.domain.models.reasoning import EngineResult, Hypothesis, ConfidenceFactor
from app.agents.reasoning.prompts import HYPOTHESIS_GENERATOR_SYSTEM_PROMPT, HYPOTHESIS_GENERATOR_USER_PROMPT

class HypothesisGenerator:
    """
    Semantic LLM component.
    Uses an LLM to infer semantic meaning from gaps and correlations.
    """
    def __init__(self, llm_client=None):
        self.llm = llm_client

    async def run(self, context: ReasoningContext, correlations: list, gaps: list) -> EngineResult:
        hypotheses = []
        
        if self.llm:
            try:
                # Format evidence context directly with UUIDs
                evidence_lines = []
                valid_uuids = set()
                if context.evidence_bundle and context.evidence_bundle.evidence:
                    for ev in context.evidence_bundle.evidence:
                        uuid_str = str(ev.evidence_id)
                        valid_uuids.add(uuid_str)
                        metadata = getattr(ev, "metadata", {})
                        desc = metadata.get("description", "")
                        cam = metadata.get("camera_id", "Unknown Camera")
                        evidence_lines.append(f"UUID: {uuid_str} -> [{cam}] {desc}".strip())
                
                evidence_str = "\n".join(evidence_lines) if evidence_lines else "No authorized evidence available."

                # Format prompts
                correlations_str = json.dumps(correlations, default=str)
                gaps_str = json.dumps(gaps, default=str)
                
                response = await self.llm.ainvoke([
                    {"role": "system", "content": HYPOTHESIS_GENERATOR_SYSTEM_PROMPT},
                    {"role": "user", "content": HYPOTHESIS_GENERATOR_USER_PROMPT.format(
                        correlations=correlations_str, 
                        gaps=gaps_str,
                        evidence_aliases=evidence_str
                    )}
                ])
                raw_content = response.content.strip()
                print(f"\n--- LLM HYPOTHESIS RAW OUTPUT ---\n{raw_content}\n-----------------------------------\n")
                import re
                json_match = re.search(r'\{.*\}', raw_content, re.DOTALL)
                if json_match:
                    raw_content = json_match.group(0)
                
                try:
                    parsed = json.loads(raw_content)
                    # Enforce strict schema validation
                    from app.domain.models.reasoning import ReasoningResult
                    valid_result = ReasoningResult(**parsed)
                    parsed = valid_result.model_dump()
                except json.JSONDecodeError as e:
                    print(f"Failed to parse JSON: {e}. Raw content:\n{raw_content}")
                    return EngineResult(success=False, errors=[f"JSONDecodeError: {str(e)}"])
                except Exception as e:
                    return EngineResult(success=False, errors=[f"Schema validation error: {str(e)}"])
                
                # Check for claims in the strict format
                claims = parsed.get("claims", [])
                for claim in claims:
                    supporting_ev = []
                    for eid in claim.get("evidence_ids", []):
                        eid_str = str(eid).strip()
                        if eid_str not in valid_uuids:
                            return EngineResult(success=False, errors=[f"Claim '{claim.get('statement')}' cited invalid or hallucinated evidence UUID: {eid_str}"])
                        
                        try:
                            from uuid import UUID
                            supporting_ev.append(UUID(eid_str))
                        except ValueError as e:
                            return EngineResult(success=False, errors=[f"Claim '{claim.get('statement')}' cited malformed evidence UUID: {eid_str}"])
                            
                    hypotheses.append(Hypothesis(
                        id=uuid4(),
                        statement=claim.get("statement", ""),
                        evidence_ids=supporting_ev,
                        support_type=claim.get("support_type", "direct"),
                        confidence_factors=[ConfidenceFactor(source="HypothesisGenerator", score=claim.get("confidence", 0.5), explanation="Generated by text model")]
                    ))
                
                # If there is a direct answer, attach to explanation for later
                explanation = parsed.get("answer", "")
                if not explanation:
                    return EngineResult(success=False, errors=["Schema validation error: answer is required"])
                
                known_facts = []
                likely_facts = []
                unknown_facts = parsed.get("uncertainties", [])
                
            except Exception as e:
                return EngineResult(success=False, errors=[str(e)])
        else:
            hypotheses.append(Hypothesis(
                id=uuid4(),
                statement="Deterministic hypothesis fallback",
                evidence_ids=[],
                support_type="unknown",
                confidence_factors=[ConfidenceFactor(source="Deterministic", score=0.5, explanation="Fallback")]
            ))
            explanation = "Deterministic fallback explanation"
            unknown_facts = []
        return EngineResult(
            success=True,
            partial_output={
                "hypotheses": [h.model_dump() for h in hypotheses],
                "explanation": explanation,
                "unknown_facts": unknown_facts
            }
        )
