from abc import ABC, abstractmethod
from typing import Any

from app.schemas.context import BaseResult, Citation, VistaContext
from app.domain.models import AgentManifest


class BaseAgent(ABC):
    """
    Contract that every agent must implement to remain extensible and consistent.
    Enforces a strict lifecycle: validate -> plan -> execute -> verify -> finish.
    """
    
    @property
    @abstractmethod
    def name(self) -> str:
        """Name of the agent for routing."""
    
    @property
    @abstractmethod
    def description(self) -> str:
        """Description of the agent's capabilities."""
        
    @property
    @abstractmethod
    def manifest(self) -> "AgentManifest":
        """Manifest describing capabilities, cost, and routing rules."""

    @abstractmethod
    def validate(self, context: VistaContext) -> bool:
        """
        Validate whether this agent should run given the context and execution plan.
        """

    @abstractmethod
    async def plan(self, context: VistaContext) -> Any:
        """
        Plan the execution for this specific agent (e.g. which tools to call).
        """

    @abstractmethod
    async def execute(self, context: VistaContext, plan: Any) -> BaseResult:
        """
        Execute the agent's primary logic using the plan.
        Returns the result object (e.g. MetadataResult, VectorResult).
        """

    @abstractmethod
    def verify(self, result: BaseResult) -> bool:
        """
        Verify the result format and basic correctness before finishing.
        """

    @abstractmethod
    def finish(self, context: VistaContext, result: BaseResult) -> VistaContext:
        """
        Finalize the context with the result, metrics, and citations.
        Must return the updated context.
        """

    @abstractmethod
    def confidence(self, result: BaseResult) -> float:
        """
        Calculate a confidence score for the result generated by this agent.
        """

    @abstractmethod
    def citations(self, result: BaseResult) -> list[Citation]:
        """
        Extract citations from the result.
        """

    @abstractmethod
    def metrics(self) -> dict[str, Any]:
        """
        Return operational metrics:
        - execution_time
        - tokens
        - tool_latency
        - memory_usage
        - errors
        - retry_count
        """
